### ISSUE TITLE
EADDRNOTAVAIL error on Windows

### ISSUE THREAD

**Issue by VBen** [jhurliman/node-motionblinds#5]
I tried to use this library in windows.
the library always throws the EADDRNOTAVAIL error.

see https://stackoverflow.com/questions/43109352/node-js-udp-multicast-over-network for a solution

See https://github.com/jhurliman/node-motionblinds/pull/4 for a possible fix

**Comment by jhurliman** [comment]
Fix merged, thanks!

**Comment by ZoneMR** [comment]
I've encountered the same issue, with the library working on linux but not windows.

After investigating, the error happens on the line:

```
recvSocket.bind(UDP_PORT_RECEIVE, MULTICAST_IP)
```

Which is present on the refactored fix. Removing the MULTICAST_IP parameter from the bind call, and letting MULTICAST_IP be added to the group in the listening event is a fix.

**Comment by VBen** [comment]
@ZoneMR I opened a new Issue #12 and submitted a pull request #13 if you are interested
